keys:
  - &users:
    - &noa age14uwcg7jr637j8supjs5ehq2vyn39e0k83y4vw52644kdpq7e6veq0wd702
  - &hosts:
    - &g14-nixos age1f5n50y2jjsusuhvrw375m59sxkrnuwh6kphh3s5hzyy8wqntk4xs2gsph9
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *noa
      - *g14-nixos

